version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Madrid"
    rebase-strategy: "auto"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore(deps-actions)"
    groups:
      actions-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
